junegunn/vim-plug

- plug.vim
Related: #161 
/cc @bruno-
This commit takes advantage of `$GIT_TERMINAL_PROMPT` variable added in git 2.3.0. So if the git installed on the system is 2.3.0 or above, vim-plug will not use `git::` hack to prevent user prompt. However, the downside of the current implementation is that it runs `git --version` command on startup which should increase the startup time by a little.
> Do not inject `git::` to url when git 2.3.0 or above found

- plug.vim
This makes it easier and faster to kill spawned git processes.
Repetitive `pgrep` command for collecting PIDs is no longer required.
Unfortunately, :pgroup option is not supported on Ruby 1.8 so we can't
remove the old implementation of `killall`.
/cc @starcraftman
> Use :pgroup option when starting subprocesses

- .travis.yml
- README.md
- plug.vim
- test/test.vader
Log:
* Main difference from ruby is inside Command class, notably it
poll/sleeps on the subprocess to check output & timeout. Not overly taxing CPU.
* Otherwise, I mainly just mirrored logic into an OOP style.
* Note that due to GVim freeze, disabling use on Windows. Also, likely
other issues.
---------------------------------------
I've squashed and cleaned up the commit and everything seems to work.
One thing I should note, is that unlike ruby, the update_python function blocks (i.e. :PlugInstall when using Python).
I think it may be a difference in the Python embedded interpreter that I can't fix. We can make a ticket here to look at it, minor issue.
Hope it is to your liking @junegunn . I've mainly testing on Ubuntu 14.04, someone like @vheon maybe should do a complete re-run of …
> Python parallel plugin management.

- README.md
Just putting the link now on the front page. Wiki is up, mainly just notes on Ubuntu. Compiling should cover any generic *NIX machine. And Mac I'm told has support out of box so just left it unsaid.
> Linking to wiki.

- plug.vim
Temporary fix for #188, need to further investigate to know how broken cygwin support is.
> Disable Python on Cygwin

- .travis.yml
Two things here:
1. Vim project moving to github eventually on a permanent basis as code.google is closing. For now I believe it is a synchronized mirror while they learn/debug migrating. Changing will future proof us.
2. Took liberty of using depth=1, no problems & build time cut in half. Wish hg supported that.
> Testing changes.

- plug.vim
안녕하세요!
This is really just personal style, but I prefer my keys to be lowercase, hence this minimal change. 
Actually I wondered why it wouldn't autoload when I did `... { 'on': '<plug>(func)' }`. Could be unexpected for other users, too. :)
> Ignore case for "<Plug>"

- .travis.yml
- README.md
- plug.vim
- test/test.vader
* Minimal python code changes required.
* Now write temp file then use py(3)file.
Temp file is generated once on invoking update_python, then regenerated only on sucessful PlugUpgrade. I've tested on 3.1.2 & 3.4.0. Changes do not seem to have any impact on 2.6+ support from what I've seen.
@junegunn Do you know why my py3 (2.1.0) test run fails on that one test?
> [RFC] Support Python 2.6+ & 3.0+

- .travis.yml
- plug.vim
* Buffer updates now managed by `__main__` loop with buf_q. Entirely for neovim support.
* Synchronous neovim install temporarily provided by python installer.
Known issues:
*   No ctrl-c/interrupt support on nvim.
*   Graphical bug: neovim/python-client#103
*   ~~Travis Python 3 build segfaults.~~
@junegunn Was interested in this to respond to #104 . This PR is work in progress still need to fix segfault. Open to comments.
Open Questions:
* Readme changes? Should it be noted in the front page like: **ATTENTION NEOVIM USERS** for sync install etc...
* Should nvim +PlugInstall **require** the neovim python lib. That is to say, don't do any installation from starting to prevent asynchronous install entirely or fallback to neovim's installer?
> [RDY] Neovim Python & Synchronous +PlugInstall

- plug.vim
If a user has a custom `format.pretty` set in their gitconfig, `git show` will use it. This can cause display issues when viewing a commit after a PlugUpdate.
If you use `git show --pretty=medium` the diff displays properly. Medium is the default format when a custom format isn't set by gitconfig.
Example gitconfig:
```
[format]
pretty = format:%C(red)%h%Creset%C(yellow)%d%Creset %C(magenta)%an%Creset: %s %C(green)(%ar)%Creset
```
vim-plug display before this change:
vim-plug display after this change:
> Specify a format when `git show` displays a commit

- README.md
- plug.vim
Probably seems simple to you @junegunn but some people as I saw in an r/vim thread a while ago thought this neat. Simple way to manage dependencies of plugins that Plug can fetch.
By having it on one line, easily delete or comment plugin + deps.
> Simple dependency.

- plug.vim
Using `Plug 'scrooloose/nerdtree', { 'on':  'NERDTreeToggle' }` and reload `.vimrc`, nerdtree isn't contained `s:loaded` and cannot be rehooked.
So, I change this script for `s:loaded` containing on-demand loaded plugins when `.vimrc` is reloaded.
> Bugfix of on-demand loading

- plug.vim
Hoping you will be interested in this (obviously) and maybe try it out a bit (I've only been using it for a day).
This introduces some new mappings for `:PlugDiff`:
`J` and `K` can be used from the diff buffer to scroll the commit preview window without having to switch to it.
`<C-N>` and `<C-P>` can be used to jump straight to commit lines (sorta like jumping to files in fugitive's commit window).
I've also made the commit window `unmodifiable` and mapped `q` to `:quit` (while inside it).
This PR introduces a `s:buffocus()` utility function.  This is used to ensure that the `J` and `K` mappings will only ever scroll the commit preview window.  If you would like me to ditch it in favour of `wincmd p`--or just change its location in the file--I will oblige.
I've also documented the `<CR>` …
> PlugDiff mappings

- .travis.yml
- plug.vim
A few highlights:
* ~~Change from time.sleep to using a thread that blocks & join it. Should reduce cpu polling problem and make it faster.~~
* A lot of style improvements in the Command class and surrounding code.
* Change travis to use env instead of many ruby versions. Makes it easier to see what build broke as env can be 'nox', 'python', 'python3', or 'ruby'. Also, I think the script reads easier.
Need to spend more time investigating the time.sleep alternative. For now, I'll just increase the sleep to reduce load.
> Refactor Python Command & .travis.yml

- README.md
Neovim's autoload directory path is now considerably different from vim's.
Got impatient, squashed patch myself.
> Add install directions for using neovim

- .travis.yml
- plug.vim
- test/run
* test/run now detects best vim to use.
* travis now installs built vim into $DEPS (or $HOME/deps).
Advantages:
- Faster startup/execution.
- Travis a bit more explicit.
- Don't know if legacy support will ever be dropped, preventative.
Cons: 
- Sudo still unsupported, but don't think we will ever need.
I'll just leave this for your feedback @junegunn, if you are alright with changes its fine to go.
> Migrate travis to use new docker system.

- README.md
Just expands the path to ensure it downloads to directory we specified to md. Just had a question where user wasn't in right CWD.
> Ensure CWD isn't a factor for powershell command.

- plug.vim
Weird bug on msys2, easily fixed by just using cd instead of cwd arg.
The PlugError change is unrelated. Just makes the behavior more consistent, should have been a bit more careful re exceptions.
> Prepend cd to commands.

- plug.vim
* Trailing slash appears to break clone command.
Simple change.
> Fix #353: Not Working On Windows

- plug.vim
Previously, syntax highlighting was turned on unconditionally in the buffers opened by commands such as `:PlugUpdate`. With this commit, highlighting is not applied if the user has disabled syntax highlighting
by calling `syntax off` after `call plug#end()` in their `vimrc`.
> Only highlight vim-plug buffers if syntax highlighting is enabled

- plug.vim
This is largely a response to fix: #394. 
Maps are only bound on prepare when function is guaranteed synchronous, else delay until finish of update/install to be done in s:finish(). Avoids the accidental neovim breakage experienced in that issue.
Also, small typo with respect to the platform test, print doesn't need brackets for python 2.
TODO:
> Fix #394: Avoid problem happening.

- README.md
- plug.vim
Made changes discussed in #397. Also, put a copy of the Plug options table in the plug.vim file. I think this was suggested previously by a few people that just wanted a quick reminder, doesn't take up too much space.
@junegunn Comments?
> Fix #397: clarify in docs that GitHub is the default plugin source

- plug.vim
- test/workflow.vader
If one runs `vim +PlugUpdate` there are two calls to `syntax enable`; one from `plug#end()` in your vimrc and another from the `PlugUpdate` command itself. It seems that when you use `+PlugUpdate` via the CLI that *both* calls to `plug#end()` happen while `has('vim_starting')` is true. This causes a minor issue where syntax highlighting (for the plug.vim itself) is lost when `PlugUpdate` finishes running.
There is a gif I found in an [unrelated issue](https://github.com/junegunn/vim-plug/issues/278#issuecomment-138683431) that shows this in action.
With this patch syntax highlighting is not lost when `PlugUpdate` finishes.
> Avoid multiple `syntax enable` during Vim startup

- plug.vim
Closes #411.
This change requires [the extra scripts](https://github.com/junegunn/vim-plug/wiki/extra) that depend on the output format to be updated.
> PlugDiff to include graphical representation of commit history

- plug.vim
- test/workflow.vader
This commit extracts duplicate logic out of three installers; vimscript, ruby, and python.
Summary:
- The steps after `git fetch` or `git clone` is now done in Vimscript.
Pros.
- Better maintainability
- Easier to add/extend the features
- Fixes a bug when 'commit' option is used, submodules are updated
before the designated commit is checked out
Cons.
- The whole process takes slightly longer due to lost parallelism after pull
- Especially, submodule updates are not parallelized
- However, this shouldn't matter much in practice as there are very
few plugins that heavily rely on submodules
- ~~No streaming output (or timeout) during submodule update~~
> Refactor duplicate logic in installers

- plug.vim
Problem: When the user has non default color settings for git show,
the output is full of terminal escaping sequences
Solution: Add `--no-color` to the `git show` command
> Reset colors for git show

- plug.vim
- test/run
- test/test.vader
- test/workflow.vader
Using YouCompleteMe, I faced some cases that `PlugInstall` clones YouCompleteMe successfully, but submodules are not cloned by interrupt or some other failures. Then even if I do `PlugInstall!` or `PlugUpdate!`, vim-plug doesn't clone submodules, so I had to `cd ~/.vim/plugged/YouCompleteMe && git submodule update --init --recursive` either `rm -rf ~/.vim/plugged/YouComplete` followed by `PlugInstall` again.
This pull request makes `PlugInstall!` and `PlugUpdate!` clone submodules, but I'm not sure it's okay to make `filter` to include every item with `s:update.force`.
> Make PlugInstall!, PlugUpdate! trigger post-fetch checkout and submodule update

- README.md
YouCompleteMe's post-installation script only seems to work with python2 (this is actually mentioned in their docs).
It seems that the sample documentation uses the system default python (which is no longer always python2), so let's better be explicit about it.
> Use python2 for YCM post-installation

- README.md
- plug.vim
- test/run
- test/workflow.vader
Close #427
- No manual parsing of the expression; just uses `git tag --list <pattern>` for wildcard expansion
- *ProTip*: `{ 'tag: '*' }` will point to the latest tagged release
- Requires git 1.9.2 or above (`error: unknown option 'sort'`)
- Are we fine with this? I think it's okay, as it's probably not going to be the most popular option.
- So the test case fails on travis-ci as it comes with git 1.8.5.6.
- We can either install the latest git using ppa, or just skip the test if the version requirement is not met
- Since I'd like to make sure that vim-plug is still functional with older versions of git and Vim, so let's go with the latter.
/cc @vilhalmer
> Support wildcards in tag option

- plug.vim
Add `:silence` to all `:delete` commands to avoid filling up the message history with *"1 line less"* messages.
---
I noticed this after `:PlugUpdate`, so silencing the `:delete` in `s:log()` would have been enough. But I found 2 other unsilenced occurences and couldn't come up with a reason why they shouldn't be silenced as well.
> Silence :delete commands

- plug.vim
Having VisualHostKey enabled for ssh can cause lines containing a single "^M" character to appear in the git output, which causes E684 to be thrown if not filtered out.
This just changes a filter to ignore any sort of newline characters so that the following split should never return an empty list.
> Fixing E684 when VisualHostKey is enabled for ssh

- plug.vim
In the buffer opened by `:PlugInstall`, lines streaming the output from `git clone` have trailing whitespace, which is highlighted by default in Neovim when `list` is enabled. By disabling `list` in the buffer, this whitespace is no longer highlighted.
> Set nolist in vim-plug buffers

- plug.vim
vim-plug detects the version of git by taking the output of `git --version`, and extracting the last group of characters separated by spaces. But it fails to extract the version number from the output correctly in with Apple's version of git in macOS. This happens because Apple adds their own release number at the end of `git --version`.  So where `git --version` on say, Ubuntu shows:
```console
$ git --version
git version 2.7.4
```
`git --version` on macOS shows:
```console
$ git --version
git version 2.9.3 (Apple Git-75)
```
Here, vim-plug can't detect the version correctly for Apple's git, since it's looking at the `Git-75)` part, not `2.9.3`.
This is especially problematic for macOS, because failure to correctly detect the version of git causes vim-plug to …
> Fix git version detection.

- plug.vim
I added `nospell` to the settings of the `vim-plug` buffer. Since the user never types anything into this buffer and plugins can have weird names along with professional jargone there is no point in spell-checking anything.
> Do not check spelling in vim-plug buffers

- plug.vim
- test/workflow.vader
The `--count` and `--left-right` options seem to be in Git since before
1.7 already.
The error message is improved, and distinguishes between only being
ahead (which is the case if you could push), or being diverged (ahead
and defined).
I think it could be bad to accidentally clean/delete a local checkout
which is ahead, and therefore PlugClean is not mentioned then, which
appears to trigger it to show up in :PlugClean.
btw: what about using `@{upstream}` (Git 1.7.0) more / in general?
> git_validate: better error with checkout being ahead/diverged

- plug.vim
Recent Neovim added a huge PR that made its Partial support on par with Vim's.
Unexpected side-effect: Neovim was less strict than Vim about the lack of `dict` if the function referred to `self`.
Please see: https://github.com/neovim/neovim/issues/5763
> Neovim: use "dict" when referring to "self"

- plug.vim
This pull request is actually very similar to #497, but since it seems to have been abandoned, here you go.
I have tested under cygwin, and it works :)
In a nutshell:
1. Under Windows and Linux, there's no problem; `core.autocrlf` takes care of everything.
2. Under Cygwin, the Windows version of vim will *not* work and it will complain about `^M` everywhere.
3. I cannot configure `git` globally under cygwin, because I *want* my Windows files to be `crlf`, even though I am working in Cygwin
The solution is to have the vim plugins clone with `lf` under cygwin.
I can now SSH on my windows machine and work :)
> Fix crlf in clones under cygwin (#497)

- plug.vim
- test/regressions.vader
:PlugStatus was reporting an invalid tag when using e.g.`Plug 'fatih/vim-go', { 'tag': '*' }`
> PlugStatus showed error with wildcard tag

- plug.vim
- test/regressions.vader
- test/workflow.vader
When loading 'deoplete.nvim' for the 2nd time during InsertEnter
manually, the `s:dobufread` (or `s:lod` itself) prevents it to work
properly - likely because the plugin gets resourced.
Maybe there could be a way to force this (and reload plugins always),
but by default it seems to make sense to skip already loaded plugins.
> Load plugins only once in plug#load

- .travis.yml
Without this there is no output from Neovim on Travis.
> Travis: VADER_OUTPUT_FILE=/dev/stderr for neovim

- README.md
Long snippets are sometimes difficult to fully select in a Web browser. Hard wrapping snippets to make them easier to grab.
> make install commands easier to highlight

- .travis.yml
1. Fix Neovim bulid by using Trusty environment
2. Make sure Vim does not link to wrong Python (`/opt/python/3.5.3`)
> Fix Travis CI build (dist: trusty)

- plug.vim
Initial work to fix all escaping issues for Vim and Neovim in Windows. `tempname` is necessary to bypass Vim's regular shellescaping in both `s:system` and `s:bang` like in Vim plugin of fzf because regular Vim seems to assume that the shell options are unchanged in Windows even if all but `shell` are unset. It's possible to not require batchfiles but it means double-escaping (ie. `fzf#shellescape(fzf#shellescape(cmd))` ) for Vim and single-escaping for Neovim with the same values for shell options.
> Port fzf#shellescape to fix escaping issues in Windows

- plug.vim
> Prepend 'silent' to ':!' to avoid hit-enter prompt in GVim on Windows

- plug.vim
I think that is useful information, especially given that the error only comes from `s:git_validate` and is about different branches etc in most cases(?).
> Display not-loaded status with all plugins that have a dir

- plug.vim
- test/workflow.vader
This allows you to override the default behavior of `o` or `<cr>` binding in PlugDiff window.
```vim
" Move to preview window
autocmd! FileType vim-plug nmap <buffer> o <plug>(plug-preview)<c-w>P
````
Close #749
Close #768
> Add <plug>(plug-preview) map

- plug.vim
Colorcolumn is an option people use to make it easier for them to see if a line has the traditional 80 character limit. Since vim-plug does not respect that limit, this pull request disables the colorcolumn option.
> Unset colorcolumn in vim-plug buffer

- plug.vim
Git v2.8 introduced support for parallel fetching of submodules. This can result in a substantial performance boost when performing a `git submodule update` in a repository with many submodules, potentially further magnified when updating submodules recursively.
This commit introduces a check on the Git version to see if it supports parallel submodule fetching. If it does, we add the `--jobs=N` argument to our call to `git submodule update`, where N is `g:plug_threads` or the vim-plug default of 16.
On my `vim-plug` configuration this more than halves the initial clone time of Vim plug-ins from ~70 seconds to ~30 seconds. The [python-mode](https://github.com/python-mode/python-mode) plugin makes a particularly good test case here as it includes a whopping 11 submodules.
> Add support for parallel fetching of Git submodules

- plug.vim
- test/regressions.vader
- test/run
`for` option is useless for plugins without `plugin` directory.
Close #785
> Ignore useless use of on-demand loading

- plug.vim
- test/workflow.vader
Close #766
This can be useful if you want to install plugins to directories outside user home directory.
> Allow cloning into an empty directory

- plug.vim
- test/workflow.vader
Previously, `:PlugDiff` would show every new commit to a plugin's git
repo. This makes sense for the general case, but makes less sense when a
plugin lives in a subdirectory of the repo (and is configured with the
'rtp' option). This makes it difficult to determine which commits relate
to the plugin and which are unrelated.
This changes `:PlugDiff` to filter out any commits outside of the 'rtp'
folder.
Some consequences:
* This does not change the `:PlugUpdate` UI. This means `:PlugUpdate`
may pull down non-plugin commits, display that it has updated the
plugin, and then `:PlugDiff` will show no updates (since such commits
fall out of the 'rtp' path).
* It also means there's no UI to revert non-plugin updates, as they
don't show up in `:PlugDiff`.
Fixes #797
Test: Manual on Linux machine
> feat(diff): use 'rtp' option to filter diff

- plug.vim
Assume that the user set the shell options correctly before running vim-plug so that the user can use bash or powershell as their shell.
If this works, port the fix to fzf's Vim plugin to resolve related issues. If there's time, avoid the batchfile on Neovim or Vim jobs before porting to fzf.
Close https://github.com/junegunn/vim-plug/issues/815
> Don't override shell on Windows

- plug.vim
- test/functional.vader
- test/test.vader
Fix #815 
Fix (partial) #690
Fix https://github.com/junegunn/vim-plug/issues/831
Fix https://github.com/junegunn/vim-plug/issues/832 (issue happens on Windows for custom shell settings without this PR)
@mikelue Can you test if it works?
TODO
- require `set noshellslash`, same as cmd.exe
- fails on `do` hook after installing the repo (tested with `do` hook to install the fzf binary)  
- `shellredir` must be set to `| Out-File -Encoding utf8` 
- Still broken in 8.1.1794 so the hack in vim-plug should be ported to fzf
> Fix Windows support for Unix shells and powershell

- .travis.yml
- test/test.vader
Ubuntu Trusty reached EOL since April 2019.
Close https://github.com/junegunn/vim-plug/issues/176
> Travis: add ubuntu xenial and bionic

- .travis.yml
I don't have a mac to verify that my changes don't introduce any regressions.
Ref: https://github.com/junegunn/vim-plug/pull/860#issuecomment-521964314
`osx_image` (https://docs.travis-ci.com/user/reference/osx/#macos-version) should be recent enough to avoid outdated homebrew packages because Travis may take 5-10 mins updating homebrew.
> Travis: add macOS 10.14

- .travis.yml
Fix https://travis-ci.org/junegunn/vim-plug/jobs/573145961#L211-L217
~~I haven't had this issue when using rvm with system ruby on osx.
Supported ruby versions, based on commits from `git log src/if_ruby.c` of vim source, is >=1.8, <=2.6.~~ The issue is with Mojave. Using an older osx image fixes the issue. I used the default image because it uses High Sierra.
> Travis: use default image for osx

- plug.vim
On Windows, when wrapping a batch command with the function s:wrap_cmds(),
when calling 'chcp' to get the current code page, the code assumed that
the output was in the format "active code page: XXX" (where XXX is the
code page), whereas the actual output is localized (for instance, in
French, the output would be: "page de code active: XXX").
The parsing of the output relied on that, and this failed for a
message different from "active code page" (i.e., English).
This patch changes the parsing to split the output of chcp on the colon
instead of spaces. Assuming that the output is always in the format
"localized message: XXX", regardless of the locale, hopefully, this is
a bit more robust.
> output of chcp was not parsed correctly

- plug.vim
Fix #874 
Fix #884
Fix #885 
Related #886 
cc @gh4w
Patch is adapted from stackoverflow answer, https://stackoverflow.com/a/10535753
> Fix chcp parsing for the current codepage

- plug.vim
Fix https://github.com/junegunn/vim-plug/issues/884
`sed` is now required to parse `chcp` output. Vim can be used instead via separate child `system` call but doing it per `s:system` makes Windows slower. `chcp` parsing is fragile because of the system locale. There's no convenient way to parse out the codepage value without regex just by relying on cmd.exe builtins and default binaries in `PATH`.
If this still doesn't work, users will have to get by with ascii output only (no readable unicode symbols from console) because this is a OS problem. This applies to fzf as well because the chcp code orignated from fzf Vim plugin was meant for UTF-8 characters.
Powershell builtins could be used as an alternative to sed but using powershell on non-powershell `&shell` slows down `s:system`.
> Use chcp only if sed is in PATH

- plug.vim
Works since Neovim v0.3.0 (https://github.com/neovim/neovim/commit/5d2dd2ebe28c31f223d77355a8f9d40adfb41c82)
Fix: https://github.com/junegunn/vim-plug/issues/821
This shouldn't be necessary because the user can configure `git` to use `LF` but there is a check for cygwin/mingw/msys2 vim via `has('win32unix')`.
> Detect WSL (Neovim only)

- plug.vim
Having a trailing slash with &rtp entries is problematic when removing
them later: if loading on demand is used, s:reorg_rtp might fail to
remove the previous runtime paths.
Test case has been using maktaba (which triggers unsetting s:middle in
s:reorg_rtp), but because of the trailing slashes being used, the
previous rtp entries were not removed.
> Use s:path with s:rtp always

- plug.vim
I had issues installing/updating my plugins recently (ie. `Invalid URI`, bad index on git) but it happens randomly for the same config. My guess is that vim-plug doesn't cleanup its temporary resources well on Windows and the shellescaping is not done correctly for all shell commands :sweat_smile:  so issues like https://github.com/junegunn/vim-plug/issues/690, https://github.com/junegunn/vim-plug/issues/852, https://github.com/junegunn/vim-plug/issues/908, https://github.com/junegunn/vim-plug/issues/890 happen.
Close #890
> Fix shellescaping for git commands on Windows

- plug.vim
- test/workflow.vader
git v2.10.0 adds "log.showSignature" config
so that "git log --show-signature" runs by default.
Changing the commit format via "--pretty" does not prevent the signature
from appearing.
Only "--no-show-signature" prevents this.
Close #728
> Do not show git signatures in diff window

- plug.vim
User should fix their terminal font to display unicode characters.
Terminal programs can only use Wide String APIs.
For Vim, this requires +multi_byte feature ~~and `set encoding=utf-8`
in the user's vimrc.~~ `iconv()` and `libcallnr` to get the current codepage (can this be cached?).
Neovim always defaults to `set encoding=utf-8`.
~~vim-plug runs commands in a batchfile with utf-8 characters.
On terminal Vim, run the batchfile in a separate minimized console
to not break the terminal console.~~
https://dev.to/mattn/please-stop-hack-chcp-65001-27db
cc @mattn @junegunn 
Close https://github.com/junegunn/vim-plug/issues/908
> Don't use chcp.

- plug.vim
Close #926
This fix shouldn't be necessary
because vim-plug's buffer should always have 4 lines
but a buffer can be modified in some cases
before nvim 0.4.0 and vim v8.1.1360.
cc @GopherJ
> Validate last buffer line of g:plug_window

- plug.vim
- test/workflow.vader
The existing error message printed when `plug#end()` is called without calling `plug#begin()` doesn't make the dependence on `plug#begin()` obvious; I had to go digging in the vim-plug code to discover what I'd done wrong. This attempts to clarify the error a bit, to make it more obvious to a user.
> Clarify error message

- plug.vim
`s:system` should be safe to optimize because some commands are internal and don't rely on the shell.
Any perf changes on non-Windows OS should be negligible. Neovim supports list type command for `system` so Neovim users can expect improved performance, at least on Windows.
Related: https://github.com/junegunn/vim-plug/issues/690, https://github.com/junegunn/vim-plug/issues/852
> Support list type command for s:system to reduce batchfiles on Windows

- README.md
For consistency with unix, vim-plug should be installed to 
`~/AppData/Local/nvim-data/site/autoload` (= `~/.local/share/nvim/site/autoload/`) on windows.
`~/AppData/Local/nvim/autoload` is the equivalent of `~/.config/nvim/autoload`
> Install to nvim-data directory on windows for consistency with unix

- README.md
The installation instructions in the `README.md` aren't taking into account the XDG specifications. Since `nvim` complies with them, placing `vim-plug`'s code in the default `~/.local/share` directory wouldn't work in case the user has `XDG_DATA_HOME` explicitly set to something else.
The command is wrapped in `sh -c ''` to ensure it's run in a POSIX shell, otherwise it wouldn't work in say, Fish, because of the variable expansion.
Last line was removed upon save because I have my `nvim` set to strip blank lines off the end of the file :slightly_smiling_face:
> Comply with the XDG protocol in the README

- plug.vim
- test/run
- test/workflow.vader
Checks the result of `s:rm_rf` and lists directories that could not be removed along with the reason. Fixes #982.
> Report when PlugClean fails to remove a directory

- plug.vim
- test/functional.vader
Close https://github.com/junegunn/vim-plug/issues/995
Vim supports omitting file extensions for its option.
I omitted the file extension in Neovim's documentation for powershell.
cc @Etherian
> Support Windows shell without extension

- README.md
A tidy one liner for the powershell install command. 
Much like the unix one 😄
This just makes the powershell install command a short one-liner.
- `iwr -useb` works on any version of powershell AFAIK.
- `ni` is `New-Item` and accepts content from `iwr` via the pipe. and the `-Force` on `ni` creates directories if they don't exist.
- the single backtick is the powershell equivalent of the backslash in unix for escaping the newline.
> Update README.md (Powershell Install One-Liner)

- doc/plug.txt
This makes it so you can do `:help :Plug` and jump to the correct help docs for the :Plug command.
> Add |:Plug| tag in help docs

- README.md
- doc/plug.txt
- plug.vim
- test/workflow.vader
https://github.blog/changelog/2020-08-26-set-the-default-branch-for-newly-created-repositories/
GitHub will be change the default branch to `main` for newly created repository. vim-plug use `master` branch for the default. This change look current branch name from HEAD/ref.
> Support non-master default branch

- plug.vim
When I start `:PlugUpdate` on WIndows, some fatal errors occured. And it seems failing lock the credentail store.
https://stackoverflow.com/questions/37505843/fatal-unable-to-get-credential-storage-lock-file-exists/37907588
Certainly, I use `credential.help=store` in global config. but it is needed for others. So I add `-c credential.helper=""` to disable it on vim-plug.
> Disable credential-helper

- README.md
The Powershell installation script currently doesn't respect the XDG_DATA_HOME environment variable. The reason it look so ugly is because Powershell doesn't support turnery operators until 7.0. Currently Windows 10 ships with 5.1 and it won't be shipping the latest Powershell until a later date.
> XDG_DATA_HOME respecting powershell script

- plug.vim
Current implementation does not fix on Windows cmd.exe
https://github.com/junegunn/vim-plug/pull/1026 or https://github.com/junegunn/vim-plug/issues/1031
> Pass empty string for credential.helper

- plug.vim
- test/workflow.vader
I adapted the q mapping to mimic the behavior of GV.vim's.
This mostly affects PlugDiff and it's commit diff preview window.
Hitting q closes PlugDiff's commit preview window and PlugDiff's pane itself.
If there's a preview window available, hitting q closes it.
If there's no preview window, hitting q closes PlugDiff's pane directly.
EDIT:
Damn. I'll add tests if there's interest in merging this PR.
> Add GV.vim-style q mapping

- plug.vim
In PowerShell v6+, the executable is named `pwsh` instead of `powershell`. But in this script, not every check for PowerShell includes both `powershell` and `pwsh`.
This PR adds a function to check if a shell is PowerShell (including `powershell` and `pwsh`) and uses it around.
Fix #1065 .
> fix: recognize pwsh as powershell

- README.md
Without the `--create-dirs` option the `curl` fails if the directories do not exists
> Add --create-dirs option to flatpak installation instrictions

- plug.vim
---
c78dc4d Set --origin=origin for git clone commands
Otherwise if the user has set a `git config clone.defaultRemoteName
foo`, then vim-plug will fail to detect the latest upstream changes as
the remote will be incorrect, and will repeatedly state that the plugin
repo needs to be cleaned.
<br/>
> Set --origin=origin for git clone commands

- plug.vim
`i_CTRL-O` may change the cursor position in an unexpected way.
For example, when `autoindent` is set, the user will expect that
`i<Space><Space>asdf<CR><C-O>` will place the cursor right below `a`.
However, `<C-O>` moves the cursor to the first column of line 2.
Expected:
```
asdf
█
```
Actual:
```
asdf
█
```
Therefore, it's desirable to use `i_CTRL-\_CTRL-O`, the variant of
`i_CTRL-O` that does not move the cursor.
> Fix unexpected cursor movement on on-demand imap loading

- README.md
The user runtime directory for Vim on Windows is `~/vimfiles` by default, not `~/.vim`. While this doesn't actually affect the functionality of vim-plug, this change would indicate to Windows users that the vim-plug directory for plugins should correspond to this, rather than erroneously creating a new `.vim` folder with only `/plugged` in it. I had made this mistake myself before fixing it manually.
This change would be consistent with the installation instructions for Windows, which installs vim-plug into `~/vimfiles`:
https://github.com/junegunn/vim-plug#windows-powershell
> README: clarify plugins directory for Windows Vim users

- .gitignore
If you set up vim-plug to manage vim-plug itself, it will create a doc/tags file, which means the repo it is saved in is dirty. Fix this by adding a gitignore.
> Add gitignore so that vim-plug can be managed by vim-plug

- README.md
The https://www.travis-ci.com/ is not used now.
> update builde status icon

- plug.vim
Neovim 0.5.0 allows lua files to be used in runtime files (such as
plugin, ftdetect, etc.) as well as vimscript files. Indeed, some
plugins have `plugin/*.lua` scripts only, but not `plugin/*.vim`;
such plugins cannot be sourced and work properly if it is lazy-loaded.
> Source lua files (if any) from rtp when loading a plugin

- plug.vim
- test/workflow.vader
Fix #1005
vim-plug will now run `git remote set-head origin -a` on PlugUpdate to keep track of the default branch of the origin, so that it can still update even if the default branch has changed.
This additional command will slow down the update process, but this is the unavoidable price to pay for the correctness of the task. However, vim-plug will run checkout and merge commands in parallel, so this improvement will slightly offset the slowdown.
> Keep track of the default branch of the origin

- README.md
- doc/plug.txt
- plug.vim
- test/workflow.vader
* Open vim-plug window in a new tab not to disrupt the current window layout
* Open preview window on the right to better show the diff
If you prefer the old layout, use the following configuration:
let g:plug_window = 'vertical topleft new'
let g:plug_pwindow = 'above 12new'
> Open vim-plug window in a new tab

- README.md
- plug.vim
If you press 'q' while `PlugInstall` or `PlugUpdate` is in progress, the current version of vim-plug immediately closes its window and aborts all the running processes.
This commit enhances the 'q' map so that it doesn't close the window, but instead displays aborted tasks so that the user can press 'R' to retry aborted/skipped tasks.
Fix #1285
/cc @yous
> Allow pressing 'q' to abort the running tasks, then 'R' to retry

- plug.vim
Before this commit, commands like this -
```vim
:tab Git diff HEAD^ HEAD
```
were interpreted like this -
```vim
:Git diff HEAD^ HEAD
```
This commit fixes that issue.
> Allow command modifiers for on-demand-loading commands
