- plug.vim
Tested on:
- Vim 7.2.330
- Python 2.6.5
- Ubuntu 10.04
- Git 1.7.0.4 / 2.3.2
- https://gist.github.com/junegunn/863dcbd78eadece788cd
/cc @starcraftman @vheon 
I'm not completely sure if there's anything else to be done, but it seems like everything works as expected and the required change was kind of trivial. I'll merge after some additional tests.
> Python 2.6 compatibility

- plug.vim
Seems to fix the problem for me. I do not know how long this was an issue though.
@vheon All good for you?
Edit: Work in progress, don't actually pull until I resolve all this.
> Fix for #193 Missing status when PlugUpdate

- plug.vim
Make us work with new api. To be merged after neovim merges PR neovim/neovim#2247.
Notes:
* Disabled python & ruby on nvim. The current implementations won't work. Not sure if there's any need, since job support in nvim is mandatory.
* Jettisoned the echo Error trick in favor of just checking return code on job exit.
> New Job API

- plug.vim
(#200)
@starcraftman @yous
So here's the new upgrade code using git. What do you think?
I'm not 100% sure if it would run on Windows :confused:
> PlugUpgrade using git (close #200)

- plug.vim
Does what it says. The py path seems stable enough to remove it now. Just dead code taking up lines.
> Remove GLog.

- plug.vim
* Problem was default decoder being ascii.
> Close #262 UnicodeDecodeError

- plug.vim
- test/workflow.vader
* Force syntax files sourcing on lod_ft.
Only negative to this fix is sometimes double sourcing syntax files, not a big deal it seems.
> Fix #272 PlugUpdate and delayed loading

- .travis.yml
* Build broken by some gui_gtk link problem.
Simple fix, keeps us building HEAD.
> Fix #280: Travis Build - Vim Fails To Compile

- README.md
The install script has been changed from `install.sh` to `install.py`.
https://github.com/Valloric/YouCompleteMe/commit/1b40d683be7fdc38bf04c2e889036314551f0035
> Update YouCompleteMe install script

- plug.vim
* Instead of having a fixed sleep duration, start a thread
that monitors the subprocess.
* Started thread is joined, if process finishes thread returns
before timeout.
* Reduces time taken & CPU overhead.
Still want to do some testing with this, but I am pretty certain I solved the earlier bug with the thread_not_started loop. Just want to test it myself for a few days before merging, including error cases. On my two comps, reduces time for PlugUpdate by a 1-2 secs.
> Join a thread instead of sleeping

- README.md
New PR because I messed my fork doing silly ``git commit --amend`` :smile:
> Add a non-master branch example

- README.md
- plug.vim
- test/workflow.vader
Close #315
- Check HEAD == hash
- Hide
- Since `+PlugUpdate` already checks out the right commit, there's no reason to `git reset`
> Add support for commit hashes

- README.md
Preserving tim's commit, I've just applied fixes to it.
> Add windows install instructions

- plug.vim
Fixes the issue, need to be careful with threads during try blocks.
> Fix #318: Freezes on PlugInstall

- plug.vim
* First fix was only partial, allow drive letter changes.
> Fix #353: Not Working On Windows

- README.md
- plug.vim
- test/run
- test/workflow.vader
> PlugDiff to show pending updates as well

- README.md
Fix issue raised on old commit, discussion at: https://github.com/junegunn/vim-plug/commit/c233234bd98ffc2502ed8afd0e0fe72ab6f9f105
Thanks @timjk for the suggested fix.
> Fix powershell command.

- README.md
- plug.vim
- test/workflow.vader
> Add 'as' option

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
- README.md
As discussed in #416. Any other changes/requests? No rush so we can think on it a bit more.
I also tinkered with the README making a get help section under installation, think this is a slightly better place.
> Fix #416: Add an issue and PR template.

- plug.vim
- test/test.vader
- test/workflow.vader
> Improve git URI validation

- plug.vim
> Fix Ruby installer on Vim 8.0.0036

- plug.vim
Patch related to this issue #586 . I checked it works with spaces and UTF8 characters as well.
This is my first pull request ever please check and tell me if something wrong.
Thank you!
> Fix job_start with spaces and UTF8 in path in Windows (Vim8)

- README.md
> Update installation instruction for Neovim on Windows

- plug.vim
> Fix PlugDiff for Windows

- plug.vim
- test/test.vader
- test/workflow.vader
CI / Travis is failing currently.
> Handle new "Already up to date" msg from Git

- plug.vim
> Escape batchfile path on Windows

- README.md
- doc/plug.txt
this description is more clear about uninstalling plugins
> Change PlugClean description

- README.md
- doc/plug.txt
'Valloric/YouCompleteMe' is not exist repository.
'Valloric/YouCompleteMe' has been changed to 'ycm-core/YouCompleteMe'
> Update YCM path : Valloric -> ycm-core

- README.md
> Add path for Neovim on Windows

- plug.vim
> Delete batchfile only if it exists

- plug.vim
Windows users may have `set shellslash` in their vimrc without changing their shell.
https://www.reddit.com/r/neovim/comments/e1vl6o/plugupdate_not_working/
~~Actual fix is to port https://github.com/junegunn/fzf/commit/7a11a06cbd03353e7c0c7ddc25cd6e9fe58cef6d#diff-24d9d57e35df5afce7890f2400917919R29-R76 from fzf~~ Done. Works on Vim. Neovim breaks if `shellslash` is set. Don't know why.
> Detect shellslash on Windows

- plug.vim
+iconv or +iconv/dyn are required for iconv().
Close https://github.com/junegunn/vim-plug/issues/920
cc @DervishD
> Use iconv() only if +iconv is enabled.

- plug.vim
Continue https://github.com/junegunn/vim-plug/pull/956
> Refactor s:clone_opt to a list

- README.md
I have added installation instructions for those users that use neovim through Flatpak.
> Add Flatpak installation instructions to README.md

- plug.vim
- test/workflow.vader
> :Plug throws error for invalid option

- .travis.yml
- test/run
- test/workflow.vader
> Fix #961 tests for Vim 7.4

- plug.vim
Closes junegunn/vim-plug#1027
Please see the commit message and the linked issue for info
> Update syntax matches

- plug.vim
This resolves the issue described in #1175.
> fix: dont "filetype off" unless did_load_filetypes

- README.md
> Updated username of NERDTree plugin as it as a new name

- README.md
- doc/plug.txt
- plug.vim
Change the name of plugin author.
> README: change `scrooloose` into `preservim`

- README.md
https://github.com/orgs/community/discussions/16925
> README: Use markdown alerts
